// One-time seed data source for the pantry catalog. Each row's `priority` is a
// stock level: "essential" | "good_to_have" | "extra" (not a color). Any color
// coding (red / yellow / green) is a display concern applied on the frontend.
//
// `purchaseAmount` + `purchaseUnit` describe the smallest package the item is
// sold in ("1 kg" flour, "10 db" eggs), which the shopping list rounds recipe
// quantities up to. Both are optional and only meaningful together: rows
// without them keep the recipe quantity unchanged, so the remaining "extra"
// rows can be filled in later without touching anything else.

const PRIORITY_RANK = {
  extra: 1,
  good_to_have: 2,
  essential: 3,
};

const RAW_CATALOG_ROWS = [
  { category: "Zöldségek", priority: "essential", name: "vöröshagyma", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Zöldségek", priority: "good_to_have", name: "fokhagyma", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "good_to_have", name: "burgonya", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Zöldségek", priority: "essential", name: "lilahagyma", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Zöldségek", priority: "extra", name: "sárgarépa" },
  { category: "Zöldségek", priority: "good_to_have", name: "paprika", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "good_to_have", name: "paradicsom", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "good_to_have", name: "saláta (jégsaláta / fejes)", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "good_to_have", name: "uborka", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "gomba" },
  { category: "Zöldségek", priority: "extra", name: "káposzta" },
  { category: "Zöldségek", priority: "good_to_have", name: "brokkoli", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "spenót" },
  { category: "Zöldségek", priority: "extra", name: "édesburgonya" },
  { category: "Zöldségek", priority: "extra", name: "chili paprika" },
  { category: "Zöldségek", priority: "extra", name: "jégcsapretek" },
  { category: "Zöldségek", priority: "extra", name: "karfiol" },
  { category: "Zöldségek", priority: "extra", name: "cukkini" },
  { category: "Zöldségek", priority: "extra", name: "padlizsán" },
  { category: "Zöldségek", priority: "extra", name: "zöldhagyma" },
  { category: "Zöldségek", priority: "extra", name: "póréhagyma" },
  { category: "Zöldségek", priority: "extra", name: "cékla" },
  { category: "Zöldségek", priority: "extra", name: "kukorica" },
  { category: "Zöldségek", priority: "extra", name: "zeller" },
  { category: "Zöldségek", priority: "extra", name: "retek" },
  { category: "Zöldségek", priority: "extra", name: "karalábé" },
  { category: "Zöldségek", priority: "extra", name: "torma" },
  { category: "Zöldségek", priority: "extra", name: "kelkáposzta" },
  { category: "Zöldségek", priority: "extra", name: "bimbós kel" },
  { category: "Zöldségek", priority: "extra", name: "patisszon" },
  { category: "Zöldségek", priority: "extra", name: "zöldborsó" },
  { category: "Zöldségek", priority: "extra", name: "zöldbab" },
  { category: "Zöldségek", priority: "extra", name: "szójabab" },
  { category: "Zöldségek", priority: "extra", name: "sóska" },
  { category: "Zöldségek", priority: "extra", name: "petrezselyem (zöldség)" },
  { category: "Zöldségek", priority: "extra", name: "snidling" },
  { category: "Zöldségek", priority: "extra", name: "madársaláta" },
  { category: "Zöldségek", priority: "extra", name: "bazsalikom (zöldség)" },
  { category: "Zöldségek", priority: "extra", name: "sütőtök" },
  { category: "Zöldségek", priority: "extra", name: "spárga" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "citrom", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "lime" },
  { category: "Gyümölcsök", priority: "essential", name: "alma", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "essential", name: "banán", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "körte", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "narancs", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "mandarin", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "szőlő", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "eper", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "őszibarack", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "extra", name: "nektarin" },
  { category: "Gyümölcsök", priority: "extra", name: "görögdinnye" },
  { category: "Gyümölcsök", priority: "extra", name: "sárgadinnye" },
  { category: "Gyümölcsök", priority: "extra", name: "kivi" },
  { category: "Gyümölcsök", priority: "extra", name: "szilva" },
  { category: "Gyümölcsök", priority: "extra", name: "kajszibarack" },
  { category: "Gyümölcsök", priority: "extra", name: "cseresznye" },
  { category: "Gyümölcsök", priority: "extra", name: "meggy" },
  { category: "Gyümölcsök", priority: "extra", name: "ribizli" },
  { category: "Gyümölcsök", priority: "extra", name: "málna" },
  { category: "Gyümölcsök", priority: "extra", name: "áfonya" },
  { category: "Gyümölcsök", priority: "extra", name: "füge" },
  { category: "Gyümölcsök", priority: "extra", name: "gránátalma" },
  { category: "Gyümölcsök", priority: "extra", name: "datolya" },
  { category: "Gyümölcsök", priority: "extra", name: "kókusz" },
  { category: "Gyümölcsök", priority: "extra", name: "pomelo" },
  { category: "Gyümölcsök", priority: "extra", name: "grapefruit" },
  { category: "Gyümölcsök", priority: "extra", name: "ananász" },
  { category: "Gyümölcsök", priority: "extra", name: "mangó" },
  { category: "Gyümölcsök", priority: "extra", name: "avokádó" },
  { category: "Gyümölcsök", priority: "extra", name: "sárkánygyümölcs (pitaja)" },
  { category: "Gyümölcsök", priority: "extra", name: "papaya" },
  { category: "Gyümölcsök", priority: "extra", name: "maracuja" },
  { category: "Pékáruk", priority: "essential", name: "kenyér", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Pékáruk", priority: "extra", name: "zsemle" },
  { category: "Pékáruk", priority: "extra", name: "kifli" },
  { category: "Pékáruk", priority: "extra", name: "toast kenyér" },
  { category: "Pékáruk", priority: "extra", name: "tortilla" },
  { category: "Pékáruk", priority: "extra", name: "bagett" },
  { category: "Pékáruk", priority: "extra", name: "hamburgerzsemle" },
  { category: "Pékáruk", priority: "extra", name: "hot-dog kifli" },
  { category: "Húsfélék", priority: "essential", name: "csirkemell", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "csirkecomb" },
  { category: "Húsfélék", priority: "extra", name: "csirkeszárny" },
  { category: "Húsfélék", priority: "extra", name: "egész csirke" },
  { category: "Húsfélék", priority: "extra", name: "pulykamell" },
  { category: "Húsfélék", priority: "extra", name: "pulykasonka" },
  { category: "Húsfélék", priority: "extra", name: "sertéstarja" },
  { category: "Húsfélék", priority: "extra", name: "sertéslapocka" },
  { category: "Húsfélék", priority: "extra", name: "sertésoldalas" },
  { category: "Húsfélék", priority: "extra", name: "marhahús" },
  { category: "Húsfélék", priority: "extra", name: "darált marhahús" },
  { category: "Húsfélék", priority: "good_to_have", name: "darált sertés", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "darált vegyes hús" },
  { category: "Húsfélék", priority: "extra", name: "garnéla" },
  { category: "Húsfélék", priority: "good_to_have", name: "hal", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "szalonna", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "darált hús", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "sertéskaraj", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "essential", name: "kolbász", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "essential", name: "sonka", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "szalámi", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "virsli", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "bacon", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "párizsi", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "felvágott", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "tej", purchaseAmount: 1, purchaseUnit: "l" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "vaj / margarin", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "sajt (trappista / félkemény)", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "tejföl", purchaseAmount: 330, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "joghurt", purchaseAmount: 150, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "tojás", purchaseAmount: 10, purchaseUnit: "db" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "túró" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "tejszín", purchaseAmount: 200, purchaseUnit: "ml" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "krémsajt" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "kefir" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "író" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "mascarpone" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "ricotta" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "feta" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "mozzarella" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "pamezán" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "camambert" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "brie" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "sajtkrém" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "desszertkrém" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "tejes" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott zöldség" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott gyümölcs" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott spenót" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott borsó" },
  { category: "Fagyasztott termékek", priority: "essential", name: "fagyasztott pizza", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott hús" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott krumpli" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott hal" },
  { category: "Fagyasztott termékek", priority: "extra", name: "jégkrém" },
  { category: "Szárazáru", priority: "essential", name: "liszt", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Szárazáru", priority: "essential", name: "rizs", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Szárazáru", priority: "good_to_have", name: "tészta", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "kuszkusz" },
  { category: "Szárazáru", priority: "extra", name: "bulgur" },
  { category: "Szárazáru", priority: "good_to_have", name: "zsemlemorzsa", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "good_to_have", name: "búzadara", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "kukoricadara" },
  { category: "Szárazáru", priority: "extra", name: "lencse" },
  { category: "Szárazáru", priority: "extra", name: "szárazbab" },
  { category: "Szárazáru", priority: "extra", name: "zabpehely" },
  { category: "Szárazáru", priority: "good_to_have", name: "konzerv kukorica", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Szárazáru", priority: "extra", name: "konzerv paradicsom" },
  { category: "Szárazáru", priority: "good_to_have", name: "konzerv bab", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Szárazáru", priority: "extra", name: "konzerv csicseriborsó" },
  { category: "Szárazáru", priority: "essential", name: "étolaj", purchaseAmount: 1, purchaseUnit: "l" },
  { category: "Szárazáru", priority: "essential", name: "olívaolaj", purchaseAmount: 500, purchaseUnit: "ml" },
  { category: "Szárazáru", priority: "essential", name: "konzerv hal", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Szárazáru", priority: "good_to_have", name: "lekvár", purchaseAmount: 350, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "good_to_have", name: "méz", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "mogyoróvaj" },
  { category: "Szárazáru", priority: "good_to_have", name: "nutella", purchaseAmount: 400, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "kakaópor" },
  { category: "Szárazáru", priority: "extra", name: "élesztő" },
  { category: "Szárazáru", priority: "extra", name: "keményítő" },
  { category: "Szárazáru", priority: "extra", name: "köles" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "cukor", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "porcukor", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "vanilliacukor", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "só", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "fekete bors", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "pirospaprika", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "majoranna", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "oregánó", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "bazsalikom", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "fahéj", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "babérlevél", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "kömény", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "szójaszósz" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "mustár", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "ketchup", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "majonéz", purchaseAmount: 400, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "ecet", purchaseAmount: 1, purchaseUnit: "l" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "BBQ szósz" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "szódabikarbóna" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "sütőpor" },
  { category: "Üdítők, italok", priority: "extra", name: "ásványvíz" },
  { category: "Üdítők, italok", priority: "extra", name: "szörp" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "üdítő", purchaseAmount: 1.5, purchaseUnit: "l" },
  { category: "Üdítők, italok", priority: "extra", name: "gyümölcslé" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "sör", purchaseAmount: 500, purchaseUnit: "ml" },
  { category: "Üdítők, italok", priority: "extra", name: "fehérbor" },
  { category: "Üdítők, italok", priority: "extra", name: "vörösbor" },
  { category: "Üdítők, italok", priority: "extra", name: "vodka" },
  { category: "Üdítők, italok", priority: "extra", name: "whisky" },
  { category: "Üdítők, italok", priority: "extra", name: "pálinka" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "kávé", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "tea", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "9. Snackek", priority: "good_to_have", name: "keksz", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "csokoládé", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "chips", purchaseAmount: 150, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "sós ropogtatni való", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "mogyoró", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "extra", name: "dió" },
  { category: "9. Snackek", priority: "extra", name: "mandula" },
  { category: "9. Snackek", priority: "good_to_have", name: "napraforgómag (szotyi)", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "extra", name: "tökmag" },
  { category: "9. Snackek", priority: "good_to_have", name: "müzli", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "müzli szelet", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "9. Snackek", priority: "extra", name: "kukoricapehely" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "papírtörlő", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "mosogatószer", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "szemeteszsák", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "alufólia", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "sütőpapír", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "szivacs", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "kézmosó szappan", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "mosószer", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "toalettpapír", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "tusfürdő", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "sampon", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "fogkrém", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "fogkefe", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "tisztítószer", purchaseAmount: 1, purchaseUnit: "db" },
];

const MANUAL_SYNONYMS = {
  krumpli: "burgonya",
  krumplit: "burgonya",
  burgonyat: "burgonya",
  "edes burgonya": "édesburgonya",
  "edeskrumpli": "édesburgonya",
  "voros hagyma": "vöröshagyma",
  "piros hagyma": "vöröshagyma",
  "lila hagyma": "lilahagyma",
  "jegsalata": "saláta (jégsaláta / fejes)",
  "fejes salata": "saláta (jégsaláta / fejes)",
  salata: "saláta (jégsaláta / fejes)",
  margarin: "vaj / margarin",
  vaj: "vaj / margarin",
  trappista: "sajt (trappista / félkemény)",
  "felkemeny sajt": "sajt (trappista / félkemény)",
  "wc papir": "toalettpapír",
  "wc-papir": "toalettpapír",
  "toalett papir": "toalettpapír",
  pitaja: "sárkánygyümölcs (pitaja)",
  szotyi: "napraforgómag (szotyi)",
};

module.exports = { PRIORITY_RANK, RAW_CATALOG_ROWS, MANUAL_SYNONYMS };
