// One-time seed data source for the pantry catalog. Each row's `priority` is a
// stock level: "essential" | "good_to_have" | "extra" (not a color). Any color
// coding (red / yellow / green) is a display concern applied on the frontend.

const PRIORITY_RANK = {
  extra: 1,
  good_to_have: 2,
  essential: 3,
};

const RAW_CATALOG_ROWS = [
  { category: "Zöldségek", priority: "essential", name: "vöröshagyma" },
  { category: "Zöldségek", priority: "good_to_have", name: "fokhagyma" },
  { category: "Zöldségek", priority: "good_to_have", name: "burgonya" },
  { category: "Zöldségek", priority: "essential", name: "lilahagyma" },
  { category: "Zöldségek", priority: "extra", name: "sárgarépa" },
  { category: "Zöldségek", priority: "good_to_have", name: "paprika" },
  { category: "Zöldségek", priority: "good_to_have", name: "paradicsom" },
  { category: "Zöldségek", priority: "good_to_have", name: "saláta (jégsaláta / fejes)" },
  { category: "Zöldségek", priority: "good_to_have", name: "uborka" },
  { category: "Zöldségek", priority: "extra", name: "gomba" },
  { category: "Zöldségek", priority: "extra", name: "káposzta" },
  { category: "Zöldségek", priority: "good_to_have", name: "brokkoli" },
  { category: "Zöldségek", priority: "extra", name: "spenót" },
  { category: "Zöldségek", priority: "extra", name: "édesburgonya" },
  { category: "Zöldségek", priority: "extra", name: "chili paprika" },
  { category: "Zöldségek", priority: "extra", name: "jégcsapretek" },
  { category: "Zöldségek", priority: "extra", name: "karfiol" },
  { category: "Zöldségek", priority: "extra", name: "cukkini" },
  { category: "Zöldségek", priority: "extra", name: "padlizsán" },
  { category: "Zöldségek", priority: "extra", name: "zöldhagyma" },
  { category: "Zöldségek", priority: "extra", name: "póréhagyma" },
  { category: "Zöldségek", priority: "extra", name: "cékla" },
  { category: "Zöldségek", priority: "extra", name: "kukorica" },
  { category: "Zöldségek", priority: "extra", name: "zeller" },
  { category: "Zöldségek", priority: "extra", name: "retek" },
  { category: "Zöldségek", priority: "extra", name: "karalábé" },
  { category: "Zöldségek", priority: "extra", name: "torma" },
  { category: "Zöldségek", priority: "extra", name: "kelkáposzta" },
  { category: "Zöldségek", priority: "extra", name: "bimbós kel" },
  { category: "Zöldségek", priority: "extra", name: "patisszon" },
  { category: "Zöldségek", priority: "extra", name: "zöldborsó" },
  { category: "Zöldségek", priority: "extra", name: "zöldbab" },
  { category: "Zöldségek", priority: "extra", name: "szójabab" },
  { category: "Zöldségek", priority: "extra", name: "sóska" },
  { category: "Zöldségek", priority: "extra", name: "petrezselyem (zöldség)" },
  { category: "Zöldségek", priority: "extra", name: "snidling" },
  { category: "Zöldségek", priority: "extra", name: "madársaláta" },
  { category: "Zöldségek", priority: "extra", name: "bazsalikom (zöldség)" },
  { category: "Zöldségek", priority: "extra", name: "sütőtök" },
  { category: "Zöldségek", priority: "extra", name: "spárga" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "citrom" },
  { category: "Gyümölcsök", priority: "extra", name: "lime" },
  { category: "Gyümölcsök", priority: "essential", name: "alma" },
  { category: "Gyümölcsök", priority: "essential", name: "banán" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "körte" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "narancs" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "mandarin" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "szőlő" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "eper" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "őszibarack" },
  { category: "Gyümölcsök", priority: "extra", name: "nektarin" },
  { category: "Gyümölcsök", priority: "extra", name: "görögdinnye" },
  { category: "Gyümölcsök", priority: "extra", name: "sárgadinnye" },
  { category: "Gyümölcsök", priority: "extra", name: "kivi" },
  { category: "Gyümölcsök", priority: "extra", name: "szilva" },
  { category: "Gyümölcsök", priority: "extra", name: "kajszibarack" },
  { category: "Gyümölcsök", priority: "extra", name: "cseresznye" },
  { category: "Gyümölcsök", priority: "extra", name: "meggy" },
  { category: "Gyümölcsök", priority: "extra", name: "ribizli" },
  { category: "Gyümölcsök", priority: "extra", name: "málna" },
  { category: "Gyümölcsök", priority: "extra", name: "áfonya" },
  { category: "Gyümölcsök", priority: "extra", name: "füge" },
  { category: "Gyümölcsök", priority: "extra", name: "gránátalma" },
  { category: "Gyümölcsök", priority: "extra", name: "datolya" },
  { category: "Gyümölcsök", priority: "extra", name: "kókusz" },
  { category: "Gyümölcsök", priority: "extra", name: "pomelo" },
  { category: "Gyümölcsök", priority: "extra", name: "grapefruit" },
  { category: "Gyümölcsök", priority: "extra", name: "ananász" },
  { category: "Gyümölcsök", priority: "extra", name: "mangó" },
  { category: "Gyümölcsök", priority: "extra", name: "avokádó" },
  { category: "Gyümölcsök", priority: "extra", name: "sárkánygyümölcs (pitaja)" },
  { category: "Gyümölcsök", priority: "extra", name: "papaya" },
  { category: "Gyümölcsök", priority: "extra", name: "maracuja" },
  { category: "Pékáruk", priority: "essential", name: "kenyér" },
  { category: "Pékáruk", priority: "extra", name: "zsemle" },
  { category: "Pékáruk", priority: "extra", name: "kifli" },
  { category: "Pékáruk", priority: "extra", name: "toast kenyér" },
  { category: "Pékáruk", priority: "extra", name: "tortilla" },
  { category: "Pékáruk", priority: "extra", name: "bagett" },
  { category: "Pékáruk", priority: "extra", name: "hamburgerzsemle" },
  { category: "Pékáruk", priority: "extra", name: "hot-dog kifli" },
  { category: "Húsfélék", priority: "essential", name: "csirkemell" },
  { category: "Húsfélék", priority: "extra", name: "csirkecomb" },
  { category: "Húsfélék", priority: "extra", name: "csirkeszárny" },
  { category: "Húsfélék", priority: "extra", name: "egész csirke" },
  { category: "Húsfélék", priority: "extra", name: "pulykamell" },
  { category: "Húsfélék", priority: "extra", name: "pulykasonka" },
  { category: "Húsfélék", priority: "extra", name: "sertéstarja" },
  { category: "Húsfélék", priority: "extra", name: "sertéslapocka" },
  { category: "Húsfélék", priority: "extra", name: "sertésoldalas" },
  { category: "Húsfélék", priority: "extra", name: "marhahús" },
  { category: "Húsfélék", priority: "extra", name: "darált marhahús" },
  { category: "Húsfélék", priority: "good_to_have", name: "darált sertés" },
  { category: "Húsfélék", priority: "extra", name: "darált vegyes hús" },
  { category: "Húsfélék", priority: "extra", name: "garnéla" },
  { category: "Húsfélék", priority: "good_to_have", name: "hal" },
  { category: "Felvágottak", priority: "good_to_have", name: "szalonna" },
  { category: "Felvágottak", priority: "good_to_have", name: "darált hús" },
  { category: "Felvágottak", priority: "good_to_have", name: "sertéskaraj" },
  { category: "Felvágottak", priority: "essential", name: "kolbász" },
  { category: "Felvágottak", priority: "essential", name: "sonka" },
  { category: "Felvágottak", priority: "good_to_have", name: "szalámi" },
  { category: "Felvágottak", priority: "good_to_have", name: "virsli" },
  { category: "Felvágottak", priority: "good_to_have", name: "bacon" },
  { category: "Felvágottak", priority: "good_to_have", name: "párizsi" },
  { category: "Felvágottak", priority: "good_to_have", name: "felvágott" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "tej" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "vaj / margarin" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "sajt (trappista / félkemény)" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "tejföl" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "joghurt" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "tojás" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "túró" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "tejszín" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "krémsajt" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "kefir" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "író" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "mascarpone" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "ricotta" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "feta" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "mozzarella" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "pamezán" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "camambert" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "brie" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "sajtkrém" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "desszertkrém" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "tejes" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott zöldség" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott gyümölcs" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott spenót" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott borsó" },
  { category: "Fagyasztott termékek", priority: "essential", name: "fagyasztott pizza" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott hús" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott krumpli" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott hal" },
  { category: "Fagyasztott termékek", priority: "extra", name: "jégkrém" },
  { category: "Szárazáru", priority: "essential", name: "liszt" },
  { category: "Szárazáru", priority: "essential", name: "rizs" },
  { category: "Szárazáru", priority: "good_to_have", name: "tészta" },
  { category: "Szárazáru", priority: "extra", name: "kuszkusz" },
  { category: "Szárazáru", priority: "extra", name: "bulgur" },
  { category: "Szárazáru", priority: "good_to_have", name: "zsemlemorzsa" },
  { category: "Szárazáru", priority: "good_to_have", name: "búzadara" },
  { category: "Szárazáru", priority: "extra", name: "kukoricadara" },
  { category: "Szárazáru", priority: "extra", name: "lencse" },
  { category: "Szárazáru", priority: "extra", name: "szárazbab" },
  { category: "Szárazáru", priority: "extra", name: "zabpehely" },
  { category: "Szárazáru", priority: "good_to_have", name: "konzerv kukorica" },
  { category: "Szárazáru", priority: "extra", name: "konzerv paradicsom" },
  { category: "Szárazáru", priority: "good_to_have", name: "konzerv bab" },
  { category: "Szárazáru", priority: "extra", name: "konzerv csicseriborsó" },
  { category: "Szárazáru", priority: "essential", name: "étolaj" },
  { category: "Szárazáru", priority: "essential", name: "olívaolaj" },
  { category: "Szárazáru", priority: "essential", name: "konzerv hal" },
  { category: "Szárazáru", priority: "good_to_have", name: "lekvár" },
  { category: "Szárazáru", priority: "good_to_have", name: "méz" },
  { category: "Szárazáru", priority: "extra", name: "mogyoróvaj" },
  { category: "Szárazáru", priority: "good_to_have", name: "nutella" },
  { category: "Szárazáru", priority: "extra", name: "kakaópor" },
  { category: "Szárazáru", priority: "extra", name: "élesztő" },
  { category: "Szárazáru", priority: "extra", name: "keményítő" },
  { category: "Szárazáru", priority: "extra", name: "köles" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "cukor" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "porcukor" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "vanilliacukor" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "só" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "fekete bors" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "pirospaprika" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "majoranna" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "oregánó" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "bazsalikom" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "fahéj" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "babérlevél" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "kömény" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "szójaszósz" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "mustár" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "ketchup" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "majonéz" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "ecet" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "BBQ szósz" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "szódabikarbóna" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "sütőpor" },
  { category: "Üdítők, italok", priority: "extra", name: "ásványvíz" },
  { category: "Üdítők, italok", priority: "extra", name: "szörp" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "üdítő" },
  { category: "Üdítők, italok", priority: "extra", name: "gyümölcslé" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "sör" },
  { category: "Üdítők, italok", priority: "extra", name: "fehérbor" },
  { category: "Üdítők, italok", priority: "extra", name: "vörösbor" },
  { category: "Üdítők, italok", priority: "extra", name: "vodka" },
  { category: "Üdítők, italok", priority: "extra", name: "whisky" },
  { category: "Üdítők, italok", priority: "extra", name: "pálinka" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "kávé" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "tea" },
  { category: "9. Snackek", priority: "good_to_have", name: "keksz" },
  { category: "9. Snackek", priority: "good_to_have", name: "csokoládé" },
  { category: "9. Snackek", priority: "good_to_have", name: "chips" },
  { category: "9. Snackek", priority: "good_to_have", name: "sós ropogtatni való" },
  { category: "9. Snackek", priority: "good_to_have", name: "mogyoró" },
  { category: "9. Snackek", priority: "extra", name: "dió" },
  { category: "9. Snackek", priority: "extra", name: "mandula" },
  { category: "9. Snackek", priority: "good_to_have", name: "napraforgómag (szotyi)" },
  { category: "9. Snackek", priority: "extra", name: "tökmag" },
  { category: "9. Snackek", priority: "good_to_have", name: "müzli" },
  { category: "9. Snackek", priority: "good_to_have", name: "müzli szelet" },
  { category: "9. Snackek", priority: "extra", name: "kukoricapehely" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "papírtörlő" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "mosogatószer" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "szemeteszsák" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "alufólia" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "sütőpapír" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "szivacs" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "kézmosó szappan" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "mosószer" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "toalettpapír" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "tusfürdő" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "sampon" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "fogkrém" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "fogkefe" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "tisztítószer" },
];

const MANUAL_SYNONYMS = {
  krumpli: "burgonya",
  krumplit: "burgonya",
  burgonyat: "burgonya",
  "edes burgonya": "édesburgonya",
  "edeskrumpli": "édesburgonya",
  "voros hagyma": "vöröshagyma",
  "piros hagyma": "vöröshagyma",
  "lila hagyma": "lilahagyma",
  "jegsalata": "saláta (jégsaláta / fejes)",
  "fejes salata": "saláta (jégsaláta / fejes)",
  salata: "saláta (jégsaláta / fejes)",
  margarin: "vaj / margarin",
  vaj: "vaj / margarin",
  trappista: "sajt (trappista / félkemény)",
  "felkemeny sajt": "sajt (trappista / félkemény)",
  "wc papir": "toalettpapír",
  "wc-papir": "toalettpapír",
  "toalett papir": "toalettpapír",
  pitaja: "sárkánygyümölcs (pitaja)",
  szotyi: "napraforgómag (szotyi)",
};

module.exports = { PRIORITY_RANK, RAW_CATALOG_ROWS, MANUAL_SYNONYMS };
