// One-time seed data source for the pantry catalog. Each row's `priority` is a
// stock level: "essential" | "good_to_have" | "extra" (not a color). Any color
// coding (red / yellow / green) is a display concern applied on the frontend.
//
// `purchaseAmount` + `purchaseUnit` describe the smallest package the item is
// sold in ("1 kg" flour, "10 db" eggs), which the shopping list rounds recipe
// quantities up to. Both are optional and only meaningful together: rows
// without them keep the recipe quantity unchanged, so the remaining "extra"
// rows can be filled in later without touching anything else.

const RAW_CATALOG_ROWS = [
  { category: "Zöldségek", priority: "essential", name: "vöröshagyma", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Zöldségek", priority: "good_to_have", name: "fokhagyma", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "good_to_have", name: "burgonya", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Zöldségek", priority: "essential", name: "lilahagyma", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "sárgarépa", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Zöldségek", priority: "good_to_have", name: "paprika", purchaseAmount: 1, purchaseUnit: "db", aliases: ["zöldpaprika", "TV paprika", "kaliforniai paprika"] },
  { category: "Zöldségek", priority: "good_to_have", name: "paradicsom", purchaseAmount: 500, purchaseUnit: "g" },
  // Two products on two shelves, so two rows. The bare "saláta" belongs to the
  // butterhead: that is what a Hungarian recipe means when it does not say which.
  { category: "Zöldségek", priority: "good_to_have", name: "fejes saláta", purchaseAmount: 1, purchaseUnit: "db", aliases: ["fejessaláta", "saláta"] },
  { category: "Zöldségek", priority: "good_to_have", name: "jégsaláta", purchaseAmount: 1, purchaseUnit: "db", aliases: ["jég saláta"] },
  { category: "Zöldségek", priority: "good_to_have", name: "uborka", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "gomba", purchaseAmount: 500, purchaseUnit: "g", aliases: ["csiperkegomba", "csiperke"] },
  { category: "Zöldségek", priority: "extra", name: "káposzta", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "good_to_have", name: "brokkoli", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "spenót", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "édesburgonya", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "chili paprika", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["hegyes-erős paprika", "hegyes erős paprika", "piros chilipaprika", "chilipaprika", "chili"] },
  { category: "Zöldségek", priority: "extra", name: "jégcsapretek", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Zöldségek", priority: "extra", name: "karfiol", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "cukkini", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "padlizsán", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "zöldhagyma", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Zöldségek", priority: "extra", name: "póréhagyma", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "cékla", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "kukorica", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "retek", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "karalábé", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "torma", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "kelkáposzta", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "bimbós kel", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "patisszon", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "zöldborsó", purchaseAmount: 450, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "zöldbab", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "szójabab", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "sóska", purchaseAmount: 1, purchaseUnit: "csomag" },
  // Herbs that are also vegetables keep both forms. The dried spice row owns the
  // bare name, so a recipe that just says "petrezselyem" buys the sachet off the
  // shelf; the fresh bunch is reached by the "friss " prefix, which resolves as a
  // full-name alias before withoutStateWords() can strip the word.
  { category: "Zöldségek", priority: "extra", name: "petrezselyem (zöldség)", purchaseAmount: 1, purchaseUnit: "csokor", aliases: ["friss petrezselyem", "petrezselyemzöld", "petrezselyem zöld", "zöldségzöld", "zöldség zöldje", "zellerzöld"] },
  { category: "Zöldségek", priority: "extra", name: "snidling", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Zöldségek", priority: "extra", name: "madársaláta", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Zöldségek", priority: "extra", name: "bazsalikom (zöldség)", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["friss bazsalikom", "bazsalikomlevél", "bazsalikom levél"] },
  { category: "Zöldségek", priority: "extra", name: "sütőtök", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "spárga", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Zöldségek", priority: "extra", name: "gyömbér", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Zöldségek", priority: "extra", name: "zellergumó", purchaseAmount: 1, purchaseUnit: "db", aliases: ["zeller", "gumós zeller", "zeller gumó"] },
  { category: "Zöldségek", priority: "extra", name: "zellerszár", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["szárzeller"] },
  { category: "Zöldségek", priority: "extra", name: "fehérrépa", purchaseAmount: 500, purchaseUnit: "g", aliases: ["petrezselyemgyökér", "petrezselyem gyökér"] },
  { category: "Zöldségek", priority: "extra", name: "leveszöldségcsomag", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["leveszöldség", "leves zöldség", "zöldségcsomag", "levescsomag"] },
  { category: "Zöldségek", priority: "extra", name: "kapor (zöldség)", purchaseAmount: 1, purchaseUnit: "csokor", aliases: ["friss kapor", "kaporzöld", "kapor zöld"] },
  { category: "Zöldségek", priority: "extra", name: "koriander (zöldség)", purchaseAmount: 1, purchaseUnit: "csokor", aliases: ["friss koriander", "koriander zöld", "korianderzöld"] },
  { category: "Zöldségek", priority: "extra", name: "rókagomba", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Zöldségek", priority: "extra", name: "jalapeno paprika", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["jalapeno", "jalapeño"] },
  { category: "Zöldségek", priority: "extra", name: "tök", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "citrom", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "lime", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "essential", name: "alma", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "essential", name: "banán", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "körte", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "narancs", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "mandarin", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "szőlő", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "eper", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "good_to_have", name: "őszibarack", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Gyümölcsök", priority: "extra", name: "nektarin", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "görögdinnye", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "sárgadinnye", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "kivi", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "szilva", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "extra", name: "kajszibarack", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "extra", name: "cseresznye", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "extra", name: "meggy", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "extra", name: "ribizli", purchaseAmount: 125, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "extra", name: "málna", purchaseAmount: 125, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "extra", name: "áfonya", purchaseAmount: 125, purchaseUnit: "g" },
  { category: "Gyümölcsök", priority: "extra", name: "füge", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Gyümölcsök", priority: "extra", name: "gránátalma", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "datolya", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Gyümölcsök", priority: "extra", name: "kókusz", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "pomelo", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "grapefruit", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "ananász", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "mangó", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "avokádó", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "sárkánygyümölcs (pitaja)", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "papaya", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Gyümölcsök", priority: "extra", name: "maracuja", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Pékáruk", priority: "essential", name: "kenyér", purchaseAmount: 1, purchaseUnit: "db", aliases: ["ciabatta kenyér", "ciabatta", "fehér kenyér", "barna kenyér"] },
  { category: "Pékáruk", priority: "extra", name: "zsemle", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Pékáruk", priority: "extra", name: "kifli", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Pékáruk", priority: "extra", name: "toast kenyér", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Pékáruk", priority: "extra", name: "tortilla", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Pékáruk", priority: "extra", name: "bagett", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Pékáruk", priority: "extra", name: "hamburgerzsemle", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Pékáruk", priority: "extra", name: "hot-dog kifli", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Húsfélék", priority: "essential", name: "csirkemell", purchaseAmount: 500, purchaseUnit: "g", aliases: ["csirkemell filé", "csirkemellfilé"] },
  { category: "Húsfélék", priority: "extra", name: "csirkecomb", purchaseAmount: 1000, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "csirkeszárny", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "egész csirke", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Húsfélék", priority: "extra", name: "pulykamell", purchaseAmount: 500, purchaseUnit: "g", aliases: ["pulykamellfilé", "pulykamell filé"] },
  { category: "Húsfélék", priority: "extra", name: "pulykasonka", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "sertéstarja", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "sertéslapocka", purchaseAmount: 1000, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "sertésoldalas", purchaseAmount: 1000, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "marhahús", purchaseAmount: 500, purchaseUnit: "g", aliases: ["marhahús (szegy vagy lábszár)", "marha", "marhalábszár", "marhaszegy"] },
  { category: "Húsfélék", priority: "extra", name: "darált marhahús", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "good_to_have", name: "darált sertés", purchaseAmount: 500, purchaseUnit: "g", aliases: ["darált sertéshús"] },
  { category: "Húsfélék", priority: "extra", name: "darált vegyes hús", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "good_to_have", name: "darált hús", purchaseAmount: 500, purchaseUnit: "g", aliases: ["darálthús"] },
  { category: "Húsfélék", priority: "extra", name: "garnéla", purchaseAmount: 500, purchaseUnit: "g", aliases: ["garnélarák"] },
  { category: "Húsfélék", priority: "good_to_have", name: "hal", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "extra", name: "tyúk", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Húsfélék", priority: "extra", name: "velőscsont", purchaseAmount: 1, purchaseUnit: "db", aliases: ["marha velőscsont", "nagy marha velőscsont", "csontleves csont"] },
  { category: "Felvágottak", priority: "good_to_have", name: "szalonna", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Húsfélék", priority: "good_to_have", name: "sertéskaraj", purchaseAmount: 500, purchaseUnit: "g", aliases: ["sertés rövidkaraj", "rövidkaraj"] },
  { category: "Felvágottak", priority: "essential", name: "kolbász", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "essential", name: "sonka", purchaseAmount: 200, purchaseUnit: "g", aliases: ["serrano sonka", "füstölt sonka"] },
  { category: "Felvágottak", priority: "good_to_have", name: "szalámi", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "virsli", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "bacon", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "párizsi", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Felvágottak", priority: "good_to_have", name: "felvágott", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "tej", purchaseAmount: 1, purchaseUnit: "l" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "vaj", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "margarin", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "sajt (trappista / félkemény)", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "tejföl", purchaseAmount: 330, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "joghurt", purchaseAmount: 150, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "essential", name: "tojás", purchaseAmount: 10, purchaseUnit: "db" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "túró", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "good_to_have", name: "tejszín", purchaseAmount: 200, purchaseUnit: "ml", aliases: ["tejszín (30%-os)", "habtejszín"] },
  { category: "Tejtermékek, tojás", priority: "extra", name: "krémsajt", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "kefir", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "író", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "mascarpone", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "ricotta", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "feta", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "mozzarella", purchaseAmount: 125, purchaseUnit: "g" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "parmezán", purchaseAmount: 100, purchaseUnit: "g", aliases: ["pamezán", "parmezan sajt"] },
  { category: "Tejtermékek, tojás", priority: "extra", name: "camembert", purchaseAmount: 1, purchaseUnit: "db", aliases: ["camambert", "camembert sajt"] },
  { category: "Tejtermékek, tojás", priority: "extra", name: "brie", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "sajtkrém", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "desszertkrém", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "főzőtejszín", purchaseAmount: 200, purchaseUnit: "ml" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "mandulatej", purchaseAmount: 1, purchaseUnit: "l" },
  { category: "Tejtermékek, tojás", priority: "extra", name: "Manchego sajt", purchaseAmount: 150, purchaseUnit: "g", aliases: ["manchego"] },
  { category: "Tejtermékek, tojás", priority: "extra", name: "görög joghurt", purchaseAmount: 150, purchaseUnit: "g" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott zöldség", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott gyümölcs", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott spenót", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott borsó", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fagyasztott termékek", priority: "essential", name: "fagyasztott pizza", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott hús", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott krumpli", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fagyasztott termékek", priority: "extra", name: "fagyasztott hal", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fagyasztott termékek", priority: "extra", name: "jégkrém", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Fagyasztott termékek", priority: "extra", name: "leveles tészta", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["vajas élesztős leveles tészta", "réteslap", "leveles vajastészta"] },
  { category: "Szárazáru", priority: "essential", name: "liszt", purchaseAmount: 1, purchaseUnit: "kg", aliases: ["finomliszt", "búzaliszt"] },
  { category: "Szárazáru", priority: "essential", name: "rizs", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Szárazáru", priority: "good_to_have", name: "tészta", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "kuszkusz", purchaseAmount: 400, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "bulgur", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "good_to_have", name: "zsemlemorzsa", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "good_to_have", name: "búzadara", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "kukoricadara", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "lencse", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "szárazbab", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "zabpehely", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "good_to_have", name: "konzerv kukorica", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Szárazáru", priority: "extra", name: "konzerv paradicsom", purchaseAmount: 1, purchaseUnit: "db", aliases: ["paradicsom konzerv", "hámozott paradicsom", "aprított paradicsom"] },
  { category: "Szárazáru", priority: "good_to_have", name: "konzerv bab", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Szárazáru", priority: "extra", name: "konzerv csicseriborsó", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Szárazáru", priority: "essential", name: "étolaj", purchaseAmount: 1, purchaseUnit: "l", aliases: ["olaj", "napraforgóolaj", "növényi olaj"] },
  { category: "Szárazáru", priority: "essential", name: "olívaolaj", purchaseAmount: 500, purchaseUnit: "ml" },
  { category: "Szárazáru", priority: "essential", name: "konzerv hal", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Szárazáru", priority: "good_to_have", name: "lekvár", purchaseAmount: 350, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "good_to_have", name: "méz", purchaseAmount: 500, purchaseUnit: "g", aliases: ["akácméz", "virágméz"] },
  { category: "Szárazáru", priority: "extra", name: "mogyoróvaj", purchaseAmount: 350, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "good_to_have", name: "nutella", purchaseAmount: 400, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "kakaópor", purchaseAmount: 100, purchaseUnit: "g", aliases: ["holland kakaópor", "kakaó"] },
  { category: "Szárazáru", priority: "extra", name: "élesztő", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Szárazáru", priority: "extra", name: "keményítő", purchaseAmount: 200, purchaseUnit: "g", aliases: ["kukoricakeményítő", "étkezési keményítő"] },
  { category: "Szárazáru", priority: "extra", name: "köles", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "chiamag", purchaseAmount: 200, purchaseUnit: "g", aliases: ["chia mag"] },
  { category: "Szárazáru", priority: "extra", name: "juharszirup", purchaseAmount: 250, purchaseUnit: "ml" },
  { category: "Szárazáru", priority: "extra", name: "olívabogyó", purchaseAmount: 1, purchaseUnit: "db", aliases: ["olajbogyó"] },
  { category: "Szárazáru", priority: "extra", name: "paradicsompüré", purchaseAmount: 70, purchaseUnit: "g", aliases: ["paradicsom püré", "sűrített paradicsom", "passata", "paradicsompassata"] },
  { category: "Szárazáru", priority: "extra", name: "sertészsír", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Szárazáru", priority: "extra", name: "alaplé", purchaseAmount: 1, purchaseUnit: "l", aliases: ["húsleves alaplé", "csontleves alaplé"] },
  { category: "Szárazáru", priority: "extra", name: "teljeskiőrlésű liszt", purchaseAmount: 1, purchaseUnit: "kg", aliases: ["teljes kiőrlésű liszt"] },
  { category: "Szárazáru", priority: "extra", name: "cukrozatlan kakaópor", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "cukor", purchaseAmount: 1, purchaseUnit: "kg", aliases: ["kristálycukor"] },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "porcukor", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "vaníliás cukor", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["vaníliáscukor", "vanilliacukor", "vaníliacukor"] },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "só", purchaseAmount: 1, purchaseUnit: "kg" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "fekete bors", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["bors", "feketebors", "szemes bors"] },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "pirospaprika", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["piros paprika", "fűszerpaprika", "őrölt paprika", "paprikapor"] },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "majoranna", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "oregánó", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "bazsalikom", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["szárított bazsalikom", "morzsolt bazsalikom"] },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "fahéj", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "babérlevél", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "kömény", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "szójaszósz", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "mustár", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "ketchup", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "essential", name: "majonéz", purchaseAmount: 400, purchaseUnit: "g" },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "ecet", purchaseAmount: 1, purchaseUnit: "l" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "BBQ szósz", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "szódabikarbóna", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "sütőpor", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "kardamom", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "kakukkfű", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["szárított kakukkfű"] },
  // The bare name lives on the spice side on purpose: see the note on
  // "petrezselyem (zöldség)". Same for kapor, koriander and bazsalikom.
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "petrezselyem", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["szárított petrezselyem", "morzsolt petrezselyem"] },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "kapor", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["szárított kapor", "morzsolt kapor"] },
  { category: "Fűszerek, ízesítők", priority: "good_to_have", name: "koriander", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["szárított koriander", "koriandermag", "koriander mag"] },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "cayenne bors", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["cayenne", "cayenne paprika"] },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "barna cukor", purchaseAmount: 500, purchaseUnit: "g", aliases: ["nádcukor"] },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "balzsamecet", purchaseAmount: 250, purchaseUnit: "ml", aliases: ["balzsamikó", "balzsamikó ecet"] },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "vörösborecet", purchaseAmount: 500, purchaseUnit: "ml" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "dijoni mustár", purchaseAmount: 200, purchaseUnit: "g", aliases: ["dijon mustár"] },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "citromlé", purchaseAmount: 200, purchaseUnit: "ml" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "lestyán", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "levesgyöngy", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "szárított tárkony", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["tárkony"] },
  { category: "Fűszerek, ízesítők", priority: "extra", name: "vaníliaaroma", purchaseAmount: 1, purchaseUnit: "db", aliases: ["vanília aroma", "vaníliakivonat"] },
  { category: "Üdítők, italok", priority: "extra", name: "ásványvíz", purchaseAmount: 1.5, purchaseUnit: "l" },
  { category: "Üdítők, italok", priority: "extra", name: "szörp", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "üdítő", purchaseAmount: 1.5, purchaseUnit: "l" },
  { category: "Üdítők, italok", priority: "extra", name: "gyümölcslé", purchaseAmount: 1, purchaseUnit: "l" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "sör", purchaseAmount: 500, purchaseUnit: "ml" },
  { category: "Üdítők, italok", priority: "extra", name: "fehérbor", purchaseAmount: 0.75, purchaseUnit: "l" },
  { category: "Üdítők, italok", priority: "extra", name: "vörösbor", purchaseAmount: 0.75, purchaseUnit: "l" },
  { category: "Üdítők, italok", priority: "extra", name: "vodka", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Üdítők, italok", priority: "extra", name: "whisky", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Üdítők, italok", priority: "extra", name: "pálinka", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "kávé", purchaseAmount: 250, purchaseUnit: "g" },
  { category: "Üdítők, italok", priority: "good_to_have", name: "őrölt kávé", purchaseAmount: 250, purchaseUnit: "g", aliases: ["presszó kávé", "presszókávé", "darált kávé"] },
  { category: "Üdítők, italok", priority: "extra", name: "3in1 kávé", purchaseAmount: 1, purchaseUnit: "csomag", aliases: ["3 in 1 kávé", "3in1"] },
  { category: "Üdítők, italok", priority: "good_to_have", name: "tea", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "9. Snackek", priority: "good_to_have", name: "keksz", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "csokoládé", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "extra", name: "étcsokoládé", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "chips", purchaseAmount: 150, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "sós ropogtatni való", purchaseAmount: 100, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "mogyoró", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "extra", name: "dió", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "extra", name: "mandula", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "napraforgómag (szotyi)", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "extra", name: "tökmag", purchaseAmount: 200, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "müzli", purchaseAmount: 500, purchaseUnit: "g" },
  { category: "9. Snackek", priority: "good_to_have", name: "müzli szelet", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "9. Snackek", priority: "extra", name: "kukoricapehely", purchaseAmount: 375, purchaseUnit: "g" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "papírtörlő", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "mosogatószer", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "szemeteszsák", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "alufólia", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "sütőpapír", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "szivacs", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "10. Háztartási alapcikkek (konyha)", priority: "essential", name: "kézmosó szappan", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "mosószer", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "toalettpapír", purchaseAmount: 1, purchaseUnit: "csomag" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "tusfürdő", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "sampon", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "fogkrém", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "fogkefe", purchaseAmount: 1, purchaseUnit: "db" },
  { category: "11. Háztartási alapcikkek (fürdő)", priority: "essential", name: "tisztítószer", purchaseAmount: 1, purchaseUnit: "db" },
];

const MANUAL_SYNONYMS = {
  krumpli: "burgonya",
  krumplit: "burgonya",
  burgonyat: "burgonya",
  "edes burgonya": "édesburgonya",
  "edeskrumpli": "édesburgonya",
  "voros hagyma": "vöröshagyma",
  "piros hagyma": "vöröshagyma",
  "lila hagyma": "lilahagyma",
  trappista: "sajt (trappista / félkemény)",
  "felkemeny sajt": "sajt (trappista / félkemény)",
  "wc papir": "toalettpapír",
  "wc-papir": "toalettpapír",
  "toalett papir": "toalettpapír",
  pitaja: "sárkánygyümölcs (pitaja)",
  szotyi: "napraforgómag (szotyi)",
};

module.exports = { RAW_CATALOG_ROWS, MANUAL_SYNONYMS };
