export const SYSTEM_UNITS = [
  "db",
  "szem",
  "g",
  "dkg",
  "kg",
  "ml",
  "dl",
  "l",
  "tk",
  "ek",
  "csipet",
  "csokor",
  "gerezd",
  "szelet",
  "bögre",
  "pohár",
  "csomag",
  "konzerv",
  "fej",
  "szál",
  "marék",
];

// Written in the readable, accented source form on both sides. The keys are put
// through unitLookupKey() (lib/units.js) before any lookup, so an accented key
// is fine here; the values are what gets displayed, so they must stay accented.
export const UNIT_ALIASES = {
  db: "db",
  darab: "db",
  // Counted one by one but not interchangeable with "db": ten peppercorns are
  // not ten pieces of pepper. See unitInfo() in lib/units.js.
  szem: "szem",
  g: "g",
  gramm: "g",
  gram: "g",
  dkg: "dkg",
  kg: "kg",
  ml: "ml",
  dl: "dl",
  l: "l",
  liter: "l",
  tk: "tk",
  teáskanál: "tk",
  kiskanál: "tk",
  ek: "ek",
  evőkanál: "ek",
  csipet: "csipet",
  csokor: "csokor",
  gerezd: "gerezd",
  szelet: "szelet",
  bögre: "bögre",
  pohár: "pohár",
  csomag: "csomag",
  konzerv: "konzerv",
  fej: "fej",
  szál: "szál",
  marék: "marék",
};